
# action.yml
name: 'Mythril'
description: 'Run Mythril'
inputs:
  contract:
    description: 'Contract to test'
    required: true
runs:
  using: 'docker'
  image: 'mythril/myth:0.23.22'
  entrypoint: './mythril_entrypoint.sh'
  args:
    - 'analyze'
    - ${{ inputs.contract }}
    - '--execution-timeout'
    - '300'
    - '--solc-json ./remappingPaths.json'
